### ISSUE TITLE
Handle 'context' or 'specify'

### ISSUE THREAD

**Issue by DevKhaira** [iensu/mocha-cakes-2#26]
small change, but i noticed that mocha cakes 2 doesn't handle context or specify. Which could be useful when we are trying to implement this.

**Comment by dotnetprofessional** [comment]
Can you provide more details on what you mean by context or specify?

**Comment by DevKhaira** [comment]
Yes absolutely:

Context is an alias for describe
and specify is an alias for it

**Comment by dotnetprofessional** [comment]
Ok but I think you're missing the point of this library. You'd use feature or scenario in place of context or specify. If you want to use those best to use them not this? If the issue is you can't mix and match then that's a different issue but you'd want to think about why you're doing that unless its during a migration phase.

**Comment by DevKhaira** [comment]
Essentially it is a migration phase. I can't see it being a massive issue, as we can just change the definition, just would be a nice to have.
